import { useAuth } from "@/_core/hooks/useAuth";
import { AppShell } from "@/components/AppShell";
import { StatusPill } from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
const dateLabel = (value: Date | null) => value ? new Date(value).toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric" }) : "No due date";
export default function Promises() { const { isAuthenticated } = useAuth(); const [query, setQuery] = useState(""); const list = trpc.promise.list.useQuery(undefined, { enabled: isAuthenticated }); const visible = useMemo(() => (list.data ?? []).filter(({ promise }) => `${promise.title} ${promise.context ?? ""}`.toLowerCase().includes(query.toLowerCase())), [list.data, query]); return <AppShell><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#66737b]">Shared memory</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.045em]">Promises</h1><p className="mt-2 text-sm text-[#66737b]">The current agreement is clear. Changes remain visible.</p></div><Link href="/capture"><Button className="rounded-xl bg-[#1f5558] text-white hover:bg-[#18484b]"><Plus className="mr-1 h-4 w-4" />New promise</Button></Link></div><div className="mt-7 flex items-center gap-2 rounded-xl border bg-white px-3.5 py-2.5"><Search className="h-4 w-4 text-[#66737b]" /><Input value={query} onChange={event => setQuery(event.target.value)} className="h-auto border-0 p-0 shadow-none focus-visible:ring-0" placeholder="Search promises" aria-label="Search promises" /></div>{!isAuthenticated ? <p className="mt-6 text-sm text-[#66737b]">Sign in to view your private promise history.</p> : list.isLoading ? <p className="mt-6 text-sm text-[#66737b]">Loading promises…</p> : !visible.length ? <section className="mt-5 rounded-[1.25rem] border border-dashed bg-white/60 p-10 text-center"><h2 className="font-extrabold">No promises match this view.</h2><p className="mt-2 text-sm text-[#66737b]">Create a clear agreement when the conversation is fresh.</p></section> : <div className="mt-4 grid gap-3 md:grid-cols-2">{visible.map(({ promise }) => <Link key={promise.id} href={`/promises/${promise.id}`} className="rounded-2xl border bg-white p-5 shadow-[0_4px_14px_rgba(30,42,50,.035)] hover:border-[#c4d4d0]"><div className="flex justify-between gap-3"><h2 className="font-extrabold tracking-[-.025em]">{promise.title}</h2><StatusPill status={promise.status} /></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-[#66737b]">{promise.context || "No additional context."}</p><p className="mt-5 border-t pt-3 text-xs font-bold text-[#526a6b]"><CalendarDays className="mr-1 inline h-3.5 w-3.5" />{dateLabel(promise.dueAt)}</p></Link>)}</div>}</AppShell>; }
