import { useAuth } from "@/_core/hooks/useAuth";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { LogOut, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

type PreferenceKey = "invitationReminders" | "dueDateReminders" | "renegotiationReminders" | "completionReminders" | "browserNotifications" | "emailSummaries";
const labels: Array<{ key: PreferenceKey; label: string; detail: string }> = [
  { key: "invitationReminders", label: "Invitation updates", detail: "When you receive a new shared agreement." },
  { key: "dueDateReminders", label: "Due date reminders", detail: "One clear reminder before a date arrives." },
  { key: "renegotiationReminders", label: "New plan updates", detail: "When someone proposes a change." },
  { key: "completionReminders", label: "Completion acknowledgment", detail: "When an agreement is ready to be acknowledged." },
  { key: "browserNotifications", label: "Browser notifications", detail: "Optional device-level reminders you can revoke anytime." },
  { key: "emailSummaries", label: "Email summaries", detail: "A future-ready preference for low-frequency summaries." },
];

export default function Settings() {
  const { isAuthenticated } = useAuth(); const preferences = trpc.promise.reminderPreferences.useQuery(undefined, { enabled: isAuthenticated }); const update = trpc.promise.updateReminderPreferences.useMutation({ onSuccess: () => preferences.refetch(), onError: () => toast.error("That preference could not be saved.") }); const exported = trpc.promise.export.useQuery(undefined, { enabled: false }); const logout = trpc.auth.logout.useMutation(); const removeAccount = trpc.account.delete.useMutation();
  const change = async (key: PreferenceKey, value: boolean) => { if (!isAuthenticated) { startLogin(); return; } if (key === "browserNotifications" && value) { if (!("Notification" in window)) { toast.error("This browser does not support notifications."); return; } const permission = await Notification.requestPermission(); if (permission !== "granted") { toast.message("Browser notifications remain off."); return; } } update.mutate({ [key]: value }); };
  const download = async () => { if (!isAuthenticated) { startLogin(); return; } const result = await exported.refetch(); const blob = new Blob([JSON.stringify(result.data ?? [], null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "promiseos-export.json"; link.click(); URL.revokeObjectURL(url); toast.success("Your private export was downloaded."); };
  const signOut = () => logout.mutate(undefined, { onSuccess: () => window.location.assign("/") }); const deleteAccount = () => { if (!window.confirm("Delete your account? Sole promises will be deleted and shared promises anonymized.")) return; removeAccount.mutate(undefined, { onSuccess: () => window.location.assign("/") }); };
  return <AppShell><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#66737b]">Your attention, your choice</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.045em]">Settings</h1>{!isAuthenticated ? <section className="mt-7 rounded-[1.25rem] border bg-white p-6"><p className="text-sm text-[#66737b]">Sign in to manage reminders and private account data.</p><Button onClick={() => startLogin()} className="mt-4 rounded-xl bg-[#1f5558] text-white">Sign in</Button></section> : <div className="mt-7 max-w-3xl space-y-4"><section className="rounded-[1.25rem] border bg-white p-5 shadow-[0_8px_20px_rgba(30,42,50,.05)]"><h2 className="font-extrabold">Reminder preferences</h2><p className="mt-2 text-sm leading-6 text-[#66737b]">Select the few reminders that help you follow through—nothing more.</p><div className="mt-5 divide-y">{labels.map(item => <label key={item.key} className="flex items-center justify-between gap-5 py-4"><span><span className="block text-sm font-extrabold">{item.label}</span><span className="mt-1 block text-xs leading-5 text-[#66737b]">{item.detail}</span></span><Switch checked={preferences.data?.[item.key] ?? false} onCheckedChange={value => change(item.key, value)} disabled={preferences.isLoading || update.isPending} aria-label={item.label} /></label>)}</div></section><section className="rounded-[1.25rem] border bg-white p-5 shadow-[0_8px_20px_rgba(30,42,50,.05)]"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-[#1f5558]" /><div><h2 className="font-extrabold">Data & privacy</h2><p className="mt-2 text-sm leading-6 text-[#66737b]">Download your promises and events, sign out, or permanently delete your account. Shared agreements remain as anonymized records for the other participant.</p><div className="mt-5 flex flex-wrap gap-2"><Button onClick={download} variant="outline" className="rounded-xl">Export my data</Button><Button onClick={signOut} variant="outline" className="rounded-xl"><LogOut className="mr-1 h-4 w-4" />Sign out</Button><Button onClick={deleteAccount} variant="outline" className="rounded-xl border-[#e5c5be] text-[#9f3c32] hover:bg-[#fdf2ef]">Delete my account</Button></div></div></div></section></div>}</AppShell>;
}
